---

# Incoming variables
#   - terraform_root_dir
#   - terraform_task_init
#   - terraform_task_plan
#   - terraform_task_apply
#   - terraform_plan_file (optional)
#   - terraform_backend_config_file (optional)
#   - terraform_vars_files (optional)
#   - terraform_init_reconfigure (optional)
#   - terraform_extract_map (optional)

- name: Terraform init
  when: terraform_task_init
  include_tasks: terraform_init.yml

- name: Terraform plan
  when: terraform_task_plan
  include_tasks: terraform_plan.yml

- name: Terraform apply
  when: terraform_task_apply
  include_tasks: terraform_apply.yml

# Extract values from the terraform component
- name: "Extract Values"
  when: terraform_task_extract|default(false)
  include_tasks: terraform_extract.yml
  loop: "{{ terraform_extract_map | dict2items }}"
  loop_control:
    loop_var: "extract_map_item"
