---

# Incoming variables
#   - terraform_root_dir
#   - terraform_task_init
#   - terraform_task_plan
#   - terraform_task_apply
#   - terraform_plan_file (optional)
#   - terraform_backend_config_file (optional)
#   - terraform_vars_files (optional)
#   - terraform_init_reconfigure (optional)

- name: Terraform init
  when: terraform_task_init == true
  include_tasks: terraform_init.yml

- name: Terraform plan
  when: terraform_task_plan == true
  include_tasks: terraform_plan.yml

- name: Terraform apply
  when: terraform_task_apply == true
  include_tasks: terraform_apply.yml
