---

- name: Terraform apply
  command: >
    terraform apply -no-color -auto-approve
    {% if terraform_plan_file is defined %} {{ terraform_plan_file }} {% else %}
    {% if terraform_vars_files is defined and terraform_vars_files %}
    {% for filename in terraform_vars_files %} -var-file={{ filename }} {% endfor %}{% endif %}
    {% endif %}
  args:
    chdir: "{{ terraform_root_dir }}"
  register: tf_output

- name: Terraform apply output
  debug:
    var: tf_output.stdout_lines
