---

- name: Terraform apply
  command: >
    terraform apply -no-color {% if terraform_plan_file is defined %} {{ terraform_plan_file }} {% endif %}
    {% if terraform_vars_files is defined and terraform_vars_files %}{% for filename in terraform_vars_files %}
    -var-file={{ filename }} {% endfor %}{% endif %}
  args:
    chdir: "{{ terraform_root_dir }}"
  register: tf_output

- name: Terraform apply output
  debug:
    var: tf_output.stdout_lines
